<?php
/**
 * Panth LLMs.txt — /llms.json url_rewrite installer.
 *
 * @copyright Copyright (c) Panth
 */
declare(strict_types=1);

namespace Panth\LlmsTxt\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

/**
 * v1.3 follow-up patch that adds the `/llms.json` request_path row for
 * stores already upgraded past {@see InstallLlmsFullUrlRewrite}.
 *
 * That earlier patch is idempotent in shape (delete-then-insert) but
 * Magento short-circuits on `getDependencies` resolution and does not
 * re-run an already-applied patch. Splitting the new row into its own
 * patch class makes the upgrade detection automatic.
 *
 * Same delete-before-insert pattern as the parent patch — safe to run
 * multiple times.
 */
class AddLlmsJsonUrlRewrite implements DataPatchInterface
{
    private const REQUEST_PATH = 'llms.json';
    private const TARGET_PATH  = 'panth_llms/llms/json';

    public function __construct(
        private readonly ModuleDataSetupInterface $moduleDataSetup,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public static function getDependencies(): array
    {
        return [InstallLlmsFullUrlRewrite::class];
    }

    public function getAliases(): array
    {
        return [];
    }

    public function apply(): self
    {
        $this->moduleDataSetup->startSetup();

        $connection = $this->moduleDataSetup->getConnection();
        $table = $this->moduleDataSetup->getTable('url_rewrite');

        foreach ($this->storeManager->getStores(false) as $store) {
            $storeId = (int) $store->getId();
            if ($storeId <= 0) {
                continue;
            }
            try {
                $connection->delete(
                    $table,
                    [
                        'request_path = ?' => self::REQUEST_PATH,
                        'store_id = ?'     => $storeId,
                        'entity_type = ?'  => 'custom',
                    ]
                );
            } catch (\Throwable) {
                // Ignore — deletion failure is non-fatal.
            }
            try {
                $connection->insert($table, [
                    'entity_type'      => 'custom',
                    'entity_id'        => 0,
                    'request_path'     => self::REQUEST_PATH,
                    'target_path'      => self::TARGET_PATH,
                    'redirect_type'    => 0,
                    'store_id'         => $storeId,
                    'description'      => 'Panth_LlmsTxt endpoint',
                    'is_autogenerated' => 0,
                    'metadata'         => null,
                ]);
            } catch (\Throwable) {
                // Ignore duplicates / race conditions.
            }
        }

        $this->moduleDataSetup->endSetup();
        return $this;
    }
}
