<?php
declare(strict_types=1);

namespace Panth\LlmsTxt\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

class AddLlmsJsonUrlRewrite implements DataPatchInterface
{
    private const REQUEST_PATH = 'llms.json';
    private const TARGET_PATH  = 'panth_llms/llms/json';

    public function __construct(
        private readonly ModuleDataSetupInterface $moduleDataSetup,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public static function getDependencies(): array
    {
        return [InstallLlmsFullUrlRewrite::class];
    }

    public function getAliases(): array
    {
        return [];
    }

    public function apply(): self
    {
        $this->moduleDataSetup->startSetup();

        $connection = $this->moduleDataSetup->getConnection();
        $table = $this->moduleDataSetup->getTable('url_rewrite');

        foreach ($this->storeManager->getStores(false) as $store) {
            $storeId = (int) $store->getId();
            if ($storeId <= 0) {
                continue;
            }
            try {
                $connection->delete(
                    $table,
                    [
                        'request_path = ?' => self::REQUEST_PATH,
                        'store_id = ?'     => $storeId,
                        'entity_type = ?'  => 'custom',
                    ]
                );
            } catch (\Throwable) {
            }
            try {
                $connection->insert($table, [
                    'entity_type'      => 'custom',
                    'entity_id'        => 0,
                    'request_path'     => self::REQUEST_PATH,
                    'target_path'      => self::TARGET_PATH,
                    'redirect_type'    => 0,
                    'store_id'         => $storeId,
                    'description'      => 'Panth_LlmsTxt endpoint',
                    'is_autogenerated' => 0,
                    'metadata'         => null,
                ]);
            } catch (\Throwable) {
            }
        }

        $this->moduleDataSetup->endSetup();
        return $this;
    }
}
