<?php
/**
 * Panth LLMs.txt — URL rewrite installer.
 *
 * @copyright Copyright (c) Panth
 */
declare(strict_types=1);

namespace Panth\LlmsTxt\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

/**
 * Registers url_rewrite rows mapping the public paths /llms.txt and
 * /llms-full.txt to the internal Panth_LlmsTxt frontend controllers so
 * they can be served without a custom router.
 *
 * Uses raw url_rewrite inserts (rather than the UrlRewrite Service) to keep
 * the patch dependency-free and store-scoped. Idempotent on re-run.
 */
class InstallLlmsFullUrlRewrite implements DataPatchInterface
{
    /**
     * @var array<string,string> request_path => target_path
     */
    private const REWRITES = [
        'llms.txt'      => 'panth_llms/llms/index',
        'llms-full.txt' => 'panth_llms/llms/full',
    ];

    /**
     * @param ModuleDataSetupInterface $moduleDataSetup
     * @param StoreManagerInterface $storeManager
     */
    public function __construct(
        private readonly ModuleDataSetupInterface $moduleDataSetup,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    /**
     * @return array<int,string>
     */
    public static function getDependencies(): array
    {
        return [];
    }

    /**
     * @return array<int,string>
     */
    public function getAliases(): array
    {
        return [];
    }

    /**
     * Apply the patch: insert both url_rewrite rows per store.
     *
     * Legacy installs (prior to the Panth_LlmsTxt split from Panth_AdvancedSEO)
     * may contain rewrites for these request paths that target the old
     * `seo/llms/*` controllers. We first purge any existing custom rewrites
     * for these paths so the insert below always lands a fresh row pointing
     * at the new `panth_llms/llms/*` controllers. Idempotent on re-run.
     *
     * @return self
     */
    public function apply(): self
    {
        $this->moduleDataSetup->startSetup();

        $connection = $this->moduleDataSetup->getConnection();
        $table = $this->moduleDataSetup->getTable('url_rewrite');

        foreach ($this->storeManager->getStores(true) as $store) {
            $storeId = (int) $store->getId();
            foreach (self::REWRITES as $request => $target) {
                try {
                    $connection->delete(
                        $table,
                        [
                            'request_path = ?' => $request,
                            'store_id = ?'     => $storeId,
                            'entity_type = ?'  => 'custom',
                        ]
                    );
                } catch (\Throwable) {
                    // Ignore — deletion failure (FK / missing) is non-fatal.
                }
                try {
                    $connection->insert($table, [
                        'entity_type'      => 'custom',
                        'entity_id'        => 0,
                        'request_path'     => $request,
                        'target_path'      => $target,
                        'redirect_type'    => 0,
                        'store_id'         => $storeId,
                        'description'      => 'Panth_LlmsTxt endpoint',
                        'is_autogenerated' => 0,
                        'metadata'         => null,
                    ]);
                } catch (\Throwable) {
                    // Ignore duplicates / race conditions.
                }
            }
        }

        $this->moduleDataSetup->endSetup();

        return $this;
    }
}
