<?php
declare(strict_types=1);

namespace Panth\LlmsTxt\Setup\Patch\Data;

use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\Patch\DataPatchInterface;
use Magento\Store\Model\StoreManagerInterface;

class InstallLlmsFullUrlRewrite implements DataPatchInterface
{
    private const REWRITES = [
        'llms.txt'      => 'panth_llms/llms/index',
        'llms-full.txt' => 'panth_llms/llms/full',
        'llms.json'     => 'panth_llms/llms/json',
    ];

    public function __construct(
        private readonly ModuleDataSetupInterface $moduleDataSetup,
        private readonly StoreManagerInterface $storeManager
    ) {
    }

    public static function getDependencies(): array
    {
        return [];
    }

    public function getAliases(): array
    {
        return [];
    }

    public function apply(): self
    {
        $this->moduleDataSetup->startSetup();

        $connection = $this->moduleDataSetup->getConnection();
        $table = $this->moduleDataSetup->getTable('url_rewrite');

        foreach ($this->storeManager->getStores(false) as $store) {
            $storeId = (int) $store->getId();
            if ($storeId <= 0) {
                continue;
            }
            foreach (self::REWRITES as $request => $target) {
                try {
                    $connection->delete(
                        $table,
                        [
                            'request_path = ?' => $request,
                            'store_id = ?'     => $storeId,
                            'entity_type = ?'  => 'custom',
                        ]
                    );
                } catch (\Throwable) {
                }
                try {
                    $connection->insert($table, [
                        'entity_type'      => 'custom',
                        'entity_id'        => 0,
                        'request_path'     => $request,
                        'target_path'      => $target,
                        'redirect_type'    => 0,
                        'store_id'         => $storeId,
                        'description'      => 'Panth_LlmsTxt endpoint',
                        'is_autogenerated' => 0,
                        'metadata'         => null,
                    ]);
                } catch (\Throwable) {
                }
            }
        }

        $this->moduleDataSetup->endSetup();

        return $this;
    }
}
